services:
  together_backoffice_sveltekit_prod:
    image: ghcr.io/tob-group-solutions/together_backoffice_sveltekit:latest
    container_name: together_backoffice_sveltekit_prod
    restart: always
    ports:
      - "3800:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - together
      
networks:
  together:
    external: true