services:
  opinion_publica_frontend_sveltkit_staging:
    image: ghcr.io/tob-group-solutions/plataforma_opinion_publica_frontend_sveltkit:staging
    container_name: opinion_publica_frontend_sveltkit_staging
    restart: unless-stopped
    ports:
      - "3861:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - opinion_publica

networks:
  opinion_publica:
    external: true
